// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1yArf4eCkCunlp4Cno_DPzmXuEbHxng',
    appId: '1:441660458336:web:58fa030c338262af4aca05',
    messagingSenderId: '441660458336',
    projectId: 'cidade-soluciona',
    authDomain: 'cidade-soluciona.firebaseapp.com',
    storageBucket: 'cidade-soluciona.appspot.com',
    measurementId: 'G-G71LE48XQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMsWVXk8t0RWh0IyL7gmgmGhz39ayO20',
    appId: '1:441660458336:android:e7f654f7eba10bcf4aca05',
    messagingSenderId: '441660458336',
    projectId: 'cidade-soluciona',
    storageBucket: 'cidade-soluciona.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDymPdBwevOuOUXz7aAQHYyTmeaJbh5yX0',
    appId: '1:441660458336:ios:b616348aa87c3ea94aca05',
    messagingSenderId: '441660458336',
    projectId: 'cidade-soluciona',
    storageBucket: 'cidade-soluciona.appspot.com',
    iosBundleId: 'com.example.cidadeSoluciona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDymPdBwevOuOUXz7aAQHYyTmeaJbh5yX0',
    appId: '1:441660458336:ios:b616348aa87c3ea94aca05',
    messagingSenderId: '441660458336',
    projectId: 'cidade-soluciona',
    storageBucket: 'cidade-soluciona.appspot.com',
    iosBundleId: 'com.example.cidadeSoluciona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1yArf4eCkCunlp4Cno_DPzmXuEbHxng',
    appId: '1:441660458336:web:a127730d403b2d934aca05',
    messagingSenderId: '441660458336',
    projectId: 'cidade-soluciona',
    authDomain: 'cidade-soluciona.firebaseapp.com',
    storageBucket: 'cidade-soluciona.appspot.com',
    measurementId: 'G-NWF3D8FHDP',
  );
}
